### ISSUE TITLE
Compile Error: Element modifiers are not allowed in components

### ISSUE THREAD

**Issue by nsharrok** [sinankeskin/ember-kioskboard#24] opened 2020-05-13 01:46 UTC
I installed the package and immediately got this error 
```
PS D:\kiosk> ember s
Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in ember-kioskboard/components/kiosk-board.hbs

Compile Error: Element modifiers are not allowed in components

Stack Trace and Error Report: C:\Users\nsharrok\AppData\Local\Temp\2/error.dump.9300ea3810b674f0f315f0e7473a016c.log

```
Log file

```
=================================================================================

ENV Summary:

  TIME: Wed May 13 2020 11:33:12 GMT+1000 (Australian Eastern Standard Time)
  TITLE: ember
  ARGV:
  - C:\Program Files\nodejs\node.exe
  - C:\Users\nsharrok\AppData\Roaming\npm\node_modules\ember-cli\bin\ember
  - s
  EXEC_PATH: C:\Program Files\nodejs\node.exe
  TMPDIR: C:\Users\nsharrok\AppData\Local\Temp\2
  SHELL: null
  PATH:
  - C
  - \Windows\system32;C
  - \Windows;C
  - \Windows\System32\Wbem;C
  - \Windows\System32\WindowsPowerShell\v1.0\;C
  - \Program Files\Microsoft VS Code\bin;C
  - \Program Files\nodejs\;C
  - \Program Files\Java\jdk-11.0.2\bin;C
  - \Strawberry\c\bin;C
  - \Strawberry\perl\site\bin;C
  - \Strawberry\perl\bin;C
  - \Program Files\Git\cmd;C
  - \Program Files\Microsoft\Web Platform Installer\;C
  - \Perl\bin;C
  - \Program Files\Microsoft SQL Server\110\Tools\Binn\;C
  - \Users\nsharrok\AppData\Local\Programs\Python\Python38-32\Scripts\;C
  - \Users\nsharrok\AppData\Local\Programs\Python\Python38-32\;C
  - \Users\nsharrok\AppData\Local\Microsoft\WindowsApps;C
  - \Users\nsharrok\AppData\Roaming\npm
  PLATFORM: win32 x64
  FREEMEM: 461312000
  TOTALMEM: 4294496256
  UPTIME: 877824
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz - 2200
  - Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz - 2200
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.34.0
  - node: 10.15.1
  - openssl: 1.1.0j
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.23.2
  - v8: 6.8.275.32-node.12
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: Compile Error: Element modifiers are not allowed in components
    at JavaScriptCompiler.closeComponent (D:\whereis\kiosk\node_modules\ember-source\dist\ember-template-compiler.js:2650:15)
    at opcodes.forEach.op (D:\whereis\kiosk\node_modules\ember-source\dist\ember-template-compiler.js:2566:21)
    at Array.forEach (<anonymous>)
    at JavaScriptCompiler.process (D:\whereis\kiosk\node_modules\ember-source\dist\ember-template-compiler.js:2558:20)
    at Function.process (D:\whereis\kiosk\node_modules\ember-source\dist\ember-template-compiler.js:2550:23)
    at Function.compile (D:\whereis\kiosk\node_modules\ember-source\dist\ember-template-compiler.js:3055:33)
    at precompile (D:\whereis\kiosk\node_modules\ember-source\dist\ember-template-compiler.js:3645:26)
    at Object.precompile (D:\whereis\kiosk\node_modules\ember-source\dist\ember-template-compiler.js:7516:37)
    at Object.template (D:\whereis\kiosk\node_modules\ember-kioskboard\node_modules\ember-cli-htmlbars\lib\utils.js:181:38)
    at TemplateCompiler.processString (D:\whereis\kiosk\node_modules\ember-kioskboard\node_modules\ember-cli-htmlbars\lib\template-compiler-plugin.js:72:15)
  - code: [undefined]
  - codeFrame: Compile Error: Element modifiers are not allowed in components
  - errorMessage: ember-kioskboard/components/kiosk-board.hbs: Compile Error: Element modifiers are not allowed in components
        in C:\Users\nsharrok\AppData\Local\Temp\2\broccoli-5320zSJMDK6EqPrO\out-094-funnel_funnel_ember_kioskboard_addon
        at broccoli-persistent-filter:TemplateCompiler
  - errorType: Template Compiler Error
  - location:
    - column: [undefined]
    - file: ember-kioskboard/components/kiosk-board.hbs
    - line: [undefined]
    - treeDir: C:\Users\nsharrok\AppData\Local\Temp\2\broccoli-5320zSJMDK6EqPrO\out-094-funnel_funnel_ember_kioskboard_addon
  - message: ember-kioskboard/components/kiosk-board.hbs: Compile Error: Element modifiers are not allowed in components
        in C:\Users\nsharrok\AppData\Local\Temp\2\broccoli-5320zSJMDK6EqPrO\out-094-funnel_funnel_ember_kioskboard_addon
        at broccoli-persistent-filter:TemplateCompiler
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: broccoli-persistent-filter:TemplateCompiler
  - originalErrorMessage: Compile Error: Element modifiers are not allowed in components
  - stack: Error: Compile Error: Element modifiers are not allowed in components
    at JavaScriptCompiler.closeComponent (D:\whereis\kiosk\node_modules\ember-source\dist\ember-template-compiler.js:2650:15)
    at opcodes.forEach.op (D:\whereis\kiosk\node_modules\ember-source\dist\ember-template-compiler.js:2566:21)
    at Array.forEach (<anonymous>)
    at JavaScriptCompiler.process (D:\whereis\kiosk\node_modules\ember-source\dist\ember-template-compiler.js:2558:20)
    at Function.process (D:\whereis\kiosk\node_modules\ember-source\dist\ember-template-compiler.js:2550:23)
    at Function.compile (D:\whereis\kiosk\node_modules\ember-source\dist\ember-template-compiler.js:3055:33)
    at precompile (D:\whereis\kiosk\node_modules\ember-source\dist\ember-template-compiler.js:3645:26)
    at Object.precompile (D:\whereis\kiosk\node_modules\ember-source\dist\ember-template-compiler.js:7516:37)
    at Object.template (D:\whereis\kiosk\node_modules\ember-kioskboard\node_modules\ember-cli-htmlbars\lib\utils.js:181:38)
    at TemplateCompiler.processString (D:\whereis\kiosk\node_modules\ember-kioskboard\node_modules\ember-cli-htmlbars\lib\template-compiler-plugin.js:72:15)

=================================================================================

```

I hope you can figure this one out

**Comment by nsharrok** [comment] 2020-05-13 01:48
```
PS D:\kiosk> ember v
ember-cli: 3.18.0
node: 10.15.1
os: win32 x64
PS D:\whereis\kiosk>
```

**Comment by sinankeskin** [comment] 2020-06-04 21:41
Hi.

I'm so sorry for late reply. I didn't get any notification about this issue.

I've created a brand new Ember app but I couldn't reproduce the issue but I found this [issue](https://github.com/dunnkers/ember-polymer/issues/65#issuecomment-308746435).

I guess this is an glimmer-vm issue and it has been fixed now.

Could you please run `npm update` and check that again?

Thank you.

**Comment by sinankeskin** [comment] 2020-06-19 20:54
Hi @nsharrok 

Any news on this issue? I'd like to help.

**Closed** 2020-10-19 13:55 UTC
